Fix Kubernetes service finding from owner references without metadata
Kubernetes `meta/v1.OwnerReference` resources do not contain a `metadata` field and therefore we should not expect the corresponding `OpenStruct` Ruby objects to respond to `#metadata` and then recursively to `#[]=(value)`. Rather, this will result in "NoMethodError: undefined method `[]=' for nil:NilClass" a exception. However, https://github.com/kontena/k8s-client still expects any resource reference passed to `K8s::Client#get_resource` to respond to `#metadata`. To set the `metadata` field on the owner reference resource then, we need to use `K8s::Resource#merge`

Closes https://issues.redhat.com/browse/THREESCALE-7283